// <auto-generated />
using BotManager.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotManager.Db.Migrations
{
    [DbContext(typeof(BotManagerContext))]
    [Migration("20240503132106_Added Image Commands")]
    partial class AddedImageCommands
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BotManager.Db.Models.BotConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Debug")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Presence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("BotManager.Db.Models.GuildConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("BotConfigId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderTrackingConfigId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceChannelConfigId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BotConfigId");

                    b.HasIndex("ImageConfigId");

                    b.HasIndex("OrderTrackingConfigId");

                    b.HasIndex("VoiceChannelConfigId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Image.ImageConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.HasKey("Id");

                    b.ToTable("ImageConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaypalLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("ItemAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.OrderTrackingConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.HasKey("Id");

                    b.ToTable("OrderTrackingConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Voice.VoiceChannelConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<ulong>("CommandChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("VoiceCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VoiceChannelConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.GuildConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.BotConfig", null)
                        .WithMany("GuildConfigs")
                        .HasForeignKey("BotConfigId");

                    b.HasOne("BotManager.Db.Models.Modules.Image.ImageConfig", "ImageConfig")
                        .WithMany()
                        .HasForeignKey("ImageConfigId");

                    b.HasOne("BotManager.Db.Models.Modules.Order.OrderTrackingConfig", "OrderTrackingConfig")
                        .WithMany()
                        .HasForeignKey("OrderTrackingConfigId");

                    b.HasOne("BotManager.Db.Models.Modules.Voice.VoiceChannelConfig", "VoiceChannelConfig")
                        .WithMany()
                        .HasForeignKey("VoiceChannelConfigId");

                    b.Navigation("ImageConfig");

                    b.Navigation("OrderTrackingConfig");

                    b.Navigation("VoiceChannelConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.OrderItem", b =>
                {
                    b.HasOne("BotManager.Db.Models.Modules.Order.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("BotManager.Db.Models.BotConfig", b =>
                {
                    b.Navigation("GuildConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
