// <auto-generated />
using BotManager.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotManager.Db.Migrations
{
    [DbContext(typeof(BotManagerContext))]
    [Migration("20240329111349_Added Order")]
    partial class AddedOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BotManager.Db.Models.BotConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Debug")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Presence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("BotManager.Db.Models.GuildConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("BotConfigId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderTrackingConfigId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BotConfigId");

                    b.HasIndex("OrderTrackingConfigId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.OrderTrackingConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.HasKey("Id");

                    b.ToTable("OrderTrackingConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.GuildConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.BotConfig", null)
                        .WithMany("GuildConfigs")
                        .HasForeignKey("BotConfigId");

                    b.HasOne("BotManager.Db.Models.Modules.Order.OrderTrackingConfig", "OrderTrackingConfig")
                        .WithMany()
                        .HasForeignKey("OrderTrackingConfigId");

                    b.Navigation("OrderTrackingConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.BotConfig", b =>
                {
                    b.Navigation("GuildConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
