// <auto-generated />
using System;
using BotManager.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotManager.Db.Migrations
{
    [DbContext(typeof(BotManagerContext))]
    [Migration("20250822075713_Added Lan Planning")]
    partial class AddedLanPlanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BotManager.Db.Models.BotConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Debug")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Presence")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("BotManager.Db.Models.GuildConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("BotConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildLocale")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BotConfigId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.AntiSpam.AntiSpamConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("IgnorePrefixes")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("AntiSpamConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Birthdays.Birthday", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("BirthdayConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BirthdayConfigId");

                    b.ToTable("Birthdays");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Birthdays.BirthdayConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PingChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("BirthdayConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Feedback.FeedbackConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("AddReactions")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("FeedbackChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("FeedbackConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Image.ImageConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("ImageConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.LanPlanner.LanMember", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("LanPlanId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatA")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatB")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeatingGroup")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanPlanId");

                    b.ToTable("LanMembers");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.LanPlanner.LanPlan", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LanPlans");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.LanPlanner.LanPlannerConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PlannerChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("LanPlannerConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Logging.LoggingConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<ulong?>("CriticalMessageChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("LoggingChannelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("LoggingConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaypalLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("ItemAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.OrderTrackingConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("OrderTrackingConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Reactions.ReactionConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("ReactionConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Reactions.ReactionItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<int>("ReactionChance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReactionConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactionEmoji")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactionMessage")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactionTrigger")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReactionConfigId");

                    b.ToTable("ReactionItems");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.RoleRequest.RoleRequestConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("RoleRequestConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Voice.VoiceChannelConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<ulong>("CommandChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("VoiceCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("VoiceChannelConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.WatchParty.WatchPartyConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("GuildConfigId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("PingRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GuildConfigId")
                        .IsUnique();

                    b.ToTable("WatchPartyConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.GuildConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.BotConfig", "BotConfig")
                        .WithMany("GuildConfigs")
                        .HasForeignKey("BotConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.AntiSpam.AntiSpamConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("AntiSpamConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.AntiSpam.AntiSpamConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Birthdays.Birthday", b =>
                {
                    b.HasOne("BotManager.Db.Models.Modules.Birthdays.BirthdayConfig", "BirthdayConfig")
                        .WithMany("Birthdays")
                        .HasForeignKey("BirthdayConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirthdayConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Birthdays.BirthdayConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("BirthdayConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.Birthdays.BirthdayConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Feedback.FeedbackConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("FeedbackConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.Feedback.FeedbackConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Image.ImageConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("ImageConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.Image.ImageConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.LanPlanner.LanMember", b =>
                {
                    b.HasOne("BotManager.Db.Models.Modules.LanPlanner.LanPlan", "Plan")
                        .WithMany("Members")
                        .HasForeignKey("LanPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.LanPlanner.LanPlannerConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("LanPlannerConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.LanPlanner.LanPlannerConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Logging.LoggingConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("LoggingConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.Logging.LoggingConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.OrderItem", b =>
                {
                    b.HasOne("BotManager.Db.Models.Modules.Order.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.OrderTrackingConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("OrderTrackingConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.Order.OrderTrackingConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Reactions.ReactionConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("ReactionConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.Reactions.ReactionConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Reactions.ReactionItem", b =>
                {
                    b.HasOne("BotManager.Db.Models.Modules.Reactions.ReactionConfig", "ReactionConfig")
                        .WithMany("Reactions")
                        .HasForeignKey("ReactionConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReactionConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.RoleRequest.RoleRequestConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("RoleRequestConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.RoleRequest.RoleRequestConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Voice.VoiceChannelConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("VoiceChannelConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.Voice.VoiceChannelConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.WatchParty.WatchPartyConfig", b =>
                {
                    b.HasOne("BotManager.Db.Models.GuildConfig", "GuildConfig")
                        .WithOne("WatchPartyConfig")
                        .HasForeignKey("BotManager.Db.Models.Modules.WatchParty.WatchPartyConfig", "GuildConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.BotConfig", b =>
                {
                    b.Navigation("GuildConfigs");
                });

            modelBuilder.Entity("BotManager.Db.Models.GuildConfig", b =>
                {
                    b.Navigation("AntiSpamConfig");

                    b.Navigation("BirthdayConfig");

                    b.Navigation("FeedbackConfig");

                    b.Navigation("ImageConfig");

                    b.Navigation("LanPlannerConfig");

                    b.Navigation("LoggingConfig");

                    b.Navigation("OrderTrackingConfig");

                    b.Navigation("ReactionConfig");

                    b.Navigation("RoleRequestConfig");

                    b.Navigation("VoiceChannelConfig");

                    b.Navigation("WatchPartyConfig");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Birthdays.BirthdayConfig", b =>
                {
                    b.Navigation("Birthdays");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.LanPlanner.LanPlan", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Order.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BotManager.Db.Models.Modules.Reactions.ReactionConfig", b =>
                {
                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
